---
env:
  global:
    # Credentials for dockerhub automation
    - DOCKERHUB_USER=cdpci
    # DOCKERHUB_PASS=...
    - secure: "F89wTK7zOrTX1r9usNTGM4SKWZy3NUI2Q8L9REGaf03xUHG61FunZJF06sRDCfSCF150/Yssm/ERoUGhxGpnmWw/lVbjXI4UVouL95QXsF8Ow2EW7oa2GLIs6W6Q443xazYDcW7H7T5VJ6jzNXY615FqdYBEApwsU/FK8ryu7iOioOU8/VqQBkwcrzuWGtQsyQDNDaGArKgVoYTbvbLpLjIxdBfyJc185QiZVb5pzBL8brHx0sbYhANqTpvvvHd7yyXougPzwwyhiQ2q5bb8O21n+rUT8fe11FObiE7+w//A/O8yk5XDZpXRFFjPujoQ8+LmxN0S7zQrgMQ4S1X1XrjYU0McfK0rZB9wG68jtMjLeb/Cy9mbNVQfk/Em0MFllwySs9KpkUjHVIwwjPRPbkA91T2ZX4SSmH/CY+68pbswDe7A4J7t2S+p+swR8YD1u0JGlLti0EmevNEtCnYd61XvNrbRNWXLIln1IN9LgtmcKsp8XTJe0nPl5KbUXQ/ORcbbcOjWgJZLv86C1Vjk2XRM9d490TPzcH3CCJ3oAM010mrCylL1ZRwc5JYbbakTPGT5inEn2EJww7OAfWEGvrLRSvdZjVEJIUUjDnNtKp9038wNfeYDCLSAPYqBKxm7tv3v3LBMlg8g3PL1XyNmRB6jezCG8p+tCDcUpBTxDac="

services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  # Test building Dockerfile.
  - make

  # Test running the container.
  - make run

  # Wait for the container to spin up, then test that systemd is working
  - sleep 5 && make test

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"

deploy:
  provider: script
  script: docker push carlodepieri/docker-archlinux-systemd
  on:
    branch: master
