---
env:
  global:
    # POST endpoint that will trigger a Docker Hub build
    # DOCKERHUB_TRIGGER=...
    - secure: "AwsI7PbULxcUtqg8q0keXFaFpMhyMjYnbFHMx9ag1jy1zIiQr6FRAORs+14AEREcXgqWKoHuaxHQCptowAIUPip2yon2dd1CliIpogZQegVKdpaJ6G0Vc1XLKhcIft9DGSy5p5qxg/ix4Kar5v6QPcoGPTxnNefTdtxc+kLwA0ar/QAnA/1wASgoaKOmKO82boH2MtfQrcfEEuT6LJzjLCTi7gNznzEIwERG/qX6/w7eGV6Tvb4v+btGmFfFwOKqneFjEpQAdnCJOaqjWm3/LswfcqAmL8DikSSDjEhEovZXKv8fWQccVW1XHsmEWEvkllSfFo6RdrqEEWu5j8fwcsvdSO4KNvxyU5QR5DHP0kP9hIbex8VbMmuoDelBKLIwnOYlC2VK61CTvZi+n2JgccPnUki1euP69BNHQhwHAoqVXtowM6boji1fEKjlr85UzZwEm/1QbKn5WE1neOorCtgGNtGamUxBWkBXLFjSuC8ALxvx/uowvUzA6LJtuH1vVASXihBASRXTDypHadibd3HuML9dU1dtwq1LutBDSulxp+V8OyBY4xImRxAvAbSwJTBh8n+Y+tbOiqaxN2AEbZz2Ah/KugMiVCo9qa9OFAdXK6JGUYmihbZETtLbHiYE/EGON6+WqB3R8dsCURxddQGCCPeLxf+exWM09KAdr/Q="

services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  # Test building Dockerfile.
  - make

  # Test running the container.
  - make run

  # Wait for the container to spin up, then test that systemd is working
  - sleep 5 && make test

deploy:
  provider: script
  script: curl -X POST "$DOCKERHUB_TRIGGER"
