---
name: CI_testing

on:
  pull_request:
  push:
    branches:
      - "testing"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build:
    name: CI_testing
    runs-on: ubuntu-latest
    env:
      using_act: ${{ github.actor == 'nektos/act'}}

    steps:
      - name: Checkout.
        uses: actions/checkout@v2

      - name: Build the image.
        run: make

      - name: Run the container.
        run: make run

      - name: Test the container.
        run: make test

      - name: Cleanup container (using Act).
        if: env.using_act == 'true'
        run: make clean-container
