---
name: prod

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  schedule:
    - cron: "0 0 1 */1 *"
    # - cron: "*/5 * * * *" # 5 min testing

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    env:
      using_act: ${{ github.actor == 'nektos/act'}}
      is_cron: ${{ github.event_name == 'schedule' }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Build the image.
        run: make

      - name: Run the container.
        run: make run

      - name: Wait for the container to spin up.
        run: sleep 10

      - name: Test the container.
        run: make test

      - name: Cleanup container (using Act).
        if: env.using_act == 'true'
        run: make clean-container

  deploy:
    needs: ci
    name: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag and push the image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            carlodepieri/docker-archlinux-systemd:${{ steps.date.outputs.date }}
            carlodepieri/docker-archlinux-systemd:latest
          target: build
